version: "3.7"
services:
  storemongodb:
    image: mongo:latest
    container_name: storemongodb
    ports:
      - "27017:27017"
    volumes:
      - ./src/main/resources/database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
